sudo: required

services:
- docker

before_install:
- docker pull centos:7.5.1804

script:
- echo "$DOCKER_USERNAME" 
- echo "$DOCKER_PASSWORD"
- >
  docker run -t --rm -v ${PWD}/rpms:/rpms centos:7.5.1804
  bash -c
  "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&
   yum install -y centos-release-gluster41.x86_64 &&
   yum install -y http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm &&
   mkdir -p /rpms &&
   yum remove -y python-chardet &&
   yum -y install --downloadonly --downloaddir=/rpms docker docker-python docker-compose python-chardet python-requests &&
   yum -y install --downloadonly --downloaddir=/rpms audit rsync jq git tcpdump nc bind-utils net-tools yum-utils libxml2-python &&
   yum -y install --downloadonly --downloaddir=/rpms glusterfs-server haproxy keepalived Percona-XtraDB-Cluster-57 &&
   yum install -y createrepo &&
   yum clean all &&
   createrepo /rpms"
- sudo chmod -R 755 ${PWD}/rpms
- docker build -t shonge/yum-repo:$TRAVIS_BRANCH .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push shonge/yum-repo:$TRAVIS_BRANCH
